package kvmclient

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
	"time"
)

// loadSyntheticFrame returns the bytes of a real (non-live) H.264 Annex-B
// elementary stream generated by FFmpeg from a synthetic color pattern:
//
//	ffmpeg -f lavfi -i color=red:size=32x32:rate=1 -frames:v 1 \
//	       -c:v libx264 -profile:v baseline -f h264 synthetic_red_32x32.h264
//
// It contains a real SPS, PPS, SEI and one IDR slice, which is exactly the
// NAL mix frameCapture.ingest needs to handle, without touching the live
// device or any real screen content.
func loadSyntheticFrame(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile("testdata/synthetic_red_32x32.h264")
	if err != nil {
		t.Fatalf("reading synthetic fixture: %v", err)
	}
	return b
}

func TestSplitAnnexBFindsAllNALTypes(t *testing.T) {
	data := loadSyntheticFrame(t)
	nalus := splitAnnexB(data)
	if len(nalus) == 0 {
		t.Fatal("expected at least one NAL unit")
	}

	var sawSPS, sawPPS, sawIDR bool
	for _, n := range nalus {
		if len(n) == 0 {
			t.Fatal("splitAnnexB produced an empty NAL unit")
		}
		switch n[0] & 0x1F {
		case naluTypeSPS:
			sawSPS = true
		case naluTypePPS:
			sawPPS = true
		case naluTypeIDR:
			sawIDR = true
		}
	}
	if !sawSPS {
		t.Error("expected to find an SPS NAL unit in the fixture")
	}
	if !sawPPS {
		t.Error("expected to find a PPS NAL unit in the fixture")
	}
	if !sawIDR {
		t.Error("expected to find an IDR NAL unit in the fixture")
	}
}

func TestSplitAnnexBRoundTripsThroughBuildAnnexB(t *testing.T) {
	data := loadSyntheticFrame(t)
	nalus := splitAnnexB(data)
	rebuilt := buildAnnexB(nalus...)

	// The rebuilt stream should re-split into the same NAL payloads, even
	// if byte-for-byte it differs from the original (start code widths can
	// vary 3 vs 4 bytes; content must not).
	again := splitAnnexB(rebuilt)
	if len(again) != len(nalus) {
		t.Fatalf("re-split produced %d NALs, want %d", len(again), len(nalus))
	}
	for i := range nalus {
		if len(again[i]) != len(nalus[i]) {
			t.Errorf("NAL %d length = %d, want %d", i, len(again[i]), len(nalus[i]))
			continue
		}
		for j := range nalus[i] {
			if again[i][j] != nalus[i][j] {
				t.Errorf("NAL %d byte %d mismatch", i, j)
				break
			}
		}
	}
}

func TestFrameCaptureIngestProducesDecodableFrame(t *testing.T) {
	fc := newFrameCapture(nil)
	data := loadSyntheticFrame(t)

	fc.ingest(data)

	fc.mu.Lock()
	got := fc.latest
	fc.mu.Unlock()

	if got == nil {
		t.Fatal("expected a captured frame after ingesting a fixture with SPS+PPS+IDR")
	}
	nalus := splitAnnexB(got.annexB)
	var sawSPS, sawPPS, sawIDR bool
	for _, n := range nalus {
		switch n[0] & 0x1F {
		case naluTypeSPS:
			sawSPS = true
		case naluTypePPS:
			sawPPS = true
		case naluTypeIDR:
			sawIDR = true
		}
	}
	if !sawSPS || !sawPPS || !sawIDR {
		t.Errorf("captured frame missing required NALs: sps=%v pps=%v idr=%v", sawSPS, sawPPS, sawIDR)
	}
}

func TestFrameCaptureIngestWithoutParameterSetsDoesNotProduceFrame(t *testing.T) {
	fc := newFrameCapture(nil)
	// An IDR slice NAL with no preceding SPS/PPS ever seen must not produce
	// a "decodable" frame - ffmpeg can't decode it standalone.
	idrOnly := buildAnnexB([]byte{0x65, 0x01, 0x02, 0x03})
	fc.ingest(idrOnly)

	fc.mu.Lock()
	got := fc.latest
	fc.mu.Unlock()
	if got != nil {
		t.Fatal("expected no captured frame when SPS/PPS are unknown")
	}
}

func TestFrameCaptureWaitForFrameUnblocksOnIngest(t *testing.T) {
	fc := newFrameCapture(nil)
	data := loadSyntheticFrame(t)

	done := make(chan struct{})
	go func() {
		defer close(done)
		fc.ingest(data)
	}()

	<-done

	fr, err := fc.waitForFrameAfter(contextWithTimeout(t, time.Second), 0)
	if err != nil {
		t.Fatalf("waitForFrame failed: %v", err)
	}
	if fr == nil || len(fr.annexB) == 0 {
		t.Fatal("expected a non-empty frame")
	}
	if time.Since(fr.capturedAt) > 5*time.Second {
		t.Errorf("capturedAt looks stale: %v", fr.capturedAt)
	}
}

func TestFrameCaptureWaitForFrameTimesOutWithoutData(t *testing.T) {
	fc := newFrameCapture(nil)
	ctx := contextWithTimeout(t, 50*time.Millisecond)
	_, err := fc.waitForFrameAfter(ctx, 0)
	if err == nil {
		t.Fatal("expected waitForFrame to time out when no frame is ever ingested")
	}
}

func TestFrameCaptureTerminalErrorWakesWaiter(t *testing.T) {
	fc := newFrameCapture(nil)
	wantErr := errors.New("video track ended")
	result := make(chan error, 1)
	ctx := contextWithTimeout(t, time.Second)
	go func() {
		_, err := fc.waitForFrameAfter(ctx, 0)
		result <- err
	}()

	fc.fail(wantErr)

	if err := <-result; !errors.Is(err, wantErr) {
		t.Fatalf("waitForFrame error = %v, want %v", err, wantErr)
	}
}

func TestFrameCaptureWaitAfterSkipsCachedGeneration(t *testing.T) {
	fc := newFrameCapture(nil)
	data := loadSyntheticFrame(t)
	fc.ingest(data)
	boundary := fc.generationBoundary()

	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	if fr, err := fc.waitForFrameAfter(ctx, boundary); err == nil || fr != nil {
		t.Fatalf("wait returned cached generation at boundary %d: frame=%v err=%v", boundary, fr, err)
	}

	fc.ingest(data)
	fr, err := fc.waitForFrameAfter(contextWithTimeout(t, time.Second), boundary)
	if err != nil {
		t.Fatalf("wait for generation after %d failed: %v", boundary, err)
	}
	if fr.generation <= boundary {
		t.Fatalf("generation = %d, want > %d", fr.generation, boundary)
	}
}

func TestFrameCaptureStoppedStreamNeverReturnsCachedFrame(t *testing.T) {
	fc := newFrameCapture(nil)
	fc.ingest(loadSyntheticFrame(t))
	boundary := fc.generationBoundary()
	wantErr := errors.New("video stream stopped")
	fc.fail(wantErr)

	fr, err := fc.waitForFrameAfter(contextWithTimeout(t, time.Second), boundary)
	if fr != nil {
		t.Fatalf("returned cached frame generation %d after stream stopped", fr.generation)
	}
	if !errors.Is(err, wantErr) {
		t.Fatalf("error = %v, want %v", err, wantErr)
	}
}

// TestFrameCaptureReadErrorIsBoundedBeforeItSurfaces checks that a
// transport error ending the RTP read loop is reduced to its category
// before it reaches a frame waiter. That error becomes the reason a
// screenshot failed, so the addresses a net.OpError carries must not
// travel with it.
func TestFrameCaptureReadErrorIsBoundedBeforeItSurfaces(t *testing.T) {
	diag := newVideoDiagnostics()
	fc := newFrameCapture(diag)

	// Shaped like the errors the Pion/UDP stack produces, using
	// documentation-range addresses (RFC 5737).
	raw := errors.New("read udp 192.0.2.10:54321->192.0.2.138:19302: connection reset by peer")
	fc.endRun(raw)

	ctx := contextWithTimeout(t, time.Second)
	_, err := fc.waitForFrameAfter(ctx, 0)
	if err == nil {
		t.Fatal("expected the ended read loop to surface an error")
	}

	got := err.Error()
	if got != "jetkvm: unreachable: device is unreachable during reading video track: video track read ended (reset)" {
		t.Errorf("surfaced error = %q, want the bounded category form", got)
	}
	for _, forbidden := range []string{"192.0.2.10", "192.0.2.138", "54321", "19302", "read udp"} {
		if strings.Contains(got, forbidden) {
			t.Errorf("surfaced error leaked %q from the raw transport error: %q", forbidden, got)
		}
	}
	if snap := diag.snapshot(nil); snap.TrackReadFailure != "reset" {
		t.Errorf("TrackReadFailure = %q, want %q", snap.TrackReadFailure, "reset")
	}
}
