// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `jetkvm` plugin's OWN CUE schema — the typed plugin_input for the
// `jetkvm` IP-KVM check/control verb.
//
// It is the SINGLE SOURCE for this plugin's params, used two ways (the same
// contract core `spec` and every other plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the
//     cue:gen pipeline, which wraps this with `package params` + `@go(params)`)
//     emits ../params/cue_types_gen.go, so the provider decodes plugin_input
//     into a TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over
//     the Describe channel; the host splices it onto the base (base ++ plugin)
//     and validates every authored `jetkvm:` step's plugin_input against
//     #JetkvmInput.
//
// An authored `jetkvm: <method>` step (scalar sugar) or
// `jetkvm: {method: …, x: …}` (map form) desugars to the INTERNAL
// plugin/plugin_input envelope, and every jetkvm-exclusive modifier lives
// HERE. The shared assertion matchers (exit_status/stdout/stderr) and the
// general `timeout` stay on core #Op, read off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type JetkvmInput struct {
	// method — the jetkvm method to dispatch (also the scalar-sugar primary:
	// `jetkvm: <method>`).
	Method JetkvmMethod `yaml:"method,omitempty" json:"method"`

	// --- connection -------------------------------------------------------
	// host — the device address ("host", "host:port", or an http(s) URL). When
	// omitted the provider falls back to the JETKVM_HOST environment variable,
	// then to the deploy's venue address. Authoring no host (and setting
	// JETKVM_HOST) keeps a device-specific hostname out of a committed plan.
	Host string `yaml:"host,omitempty" json:"host,omitempty"`

	// password — the device password. Prefer password_secret (the credential
	// store); this literal exists for ad-hoc/CI use.
	Password string `yaml:"password,omitempty" json:"password,omitempty"`

	// password_secret — the credential-store key holding the device password.
	PasswordSecret string `yaml:"password_secret,omitempty" json:"password_secret,omitempty"`

	// auth_token — an already-valid authToken session cookie value, skipping login.
	AuthToken string `yaml:"auth_token,omitempty" json:"auth_token,omitempty"`

	// allow_control — REQUIRED to be true for every mutating method (input,
	// power, USB, virtual media, config writes). Read-only methods ignore it.
	// This is the device-safety gate: a physical appliance is not disposable.
	AllowControl bool `yaml:"allow_control,omitempty" json:"allow_control,omitempty"`

	// insecure — permit a self-signed TLS certificate (the device ships
	// self-signed by default). Also implied by an http:// host.
	Insecure bool `yaml:"insecure,omitempty" json:"insecure,omitempty"`

	// --- input (keyboard/pointer) ----------------------------------------
	// text — the text `type` types.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// key — the named key `key` presses (Return, Escape, F5, Control_L, ...).
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// combo — the chord `key-combo` presses, e.g. "Control_L+Alt_L+Delete".
	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	// hold_ms — how long `key`/`combo` holds before release (default 40).
	HoldMs int `yaml:"hold_ms,omitempty" json:"hold_ms,omitempty"`

	// x / y — ABSOLUTE HID pointer coordinates for click/mouse/move/drag, in
	// the device's [0,32767] range — NOT desktop pixels. Map a desktop pixel
	// (px,py) on a WxH screen to (px*32767/(W-1), py*32767/(H-1)); the centre of
	// a 1920x1080 screen is about (16384,16384).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// from_x / from_y — drag start coordinates.
	FromX int `yaml:"from_x,omitempty" json:"from_x,omitempty"`

	FromY int `yaml:"from_y,omitempty" json:"from_y,omitempty"`

	// button — pointer button (default left). Used by `click` and `drag`.
	// `move`/`mouse` are pure position moves and NEVER press a button, so a
	// `button:` on them is validated but not sent.
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// scroll_x / scroll_y — wheel deltas (scroll).
	ScrollX int `yaml:"scroll_x,omitempty" json:"scroll_x,omitempty"`

	ScrollY int `yaml:"scroll_y,omitempty" json:"scroll_y,omitempty"`

	// macro — the ordered key-steps a `macro` method executes.
	Macro []JetkvmMacroStep `yaml:"macro,omitempty" json:"macro,omitempty"`

	// --- power / ATX / DC -------------------------------------------------
	// action — the per-method action verb. It is a CUE enum of every action the
	// catalog accepts ACROSS the action-bearing methods (power, dc-power,
	// virtual-media, set-video, set-display, set-audio), so a typo is rejected at
	// validate time and the valid verbs are generated into the docs. The
	// method-SPECIFIC subset (e.g. `power` accepts only power-short/power-long/
	// reset) is enforced at dispatch, because a single shared field cannot carry
	// per-method disjunctions without degrading `cue exp gengotypes` (SDD — see
	// #JetkvmAction's note).
	Action JetkvmAction `yaml:"action,omitempty" json:"action,omitempty"`

	// --- virtual media ----------------------------------------------------
	// media_url — the HTTP(S) URL `virtual-media` mounts.
	MediaUrl string `yaml:"media_url,omitempty" json:"media_url,omitempty"`

	// media_file — the device-storage filename `virtual-media` mounts/deletes.
	MediaFile string `yaml:"media_file,omitempty" json:"media_file,omitempty"`

	// media_mode — cdrom | disk.
	MediaMode string `yaml:"media_mode,omitempty" json:"media_mode,omitempty"`

	// --- usb --------------------------------------------------------------
	// usb_device — the virtual USB device class to enable/disable.
	UsbDevice string `yaml:"usb_device,omitempty" json:"usb_device,omitempty"`

	// usb_enabled — enable/disable the addressed usb_device (or the whole
	// emulation bus for `usb-emulation`).
	UsbEnabled bool `yaml:"usb_enabled,omitempty" json:"usb_enabled,omitempty"`

	// --- config / network -------------------------------------------------
	// value — the generic scalar a set-style method writes (rotation, layout,
	// codec, factor, log level, extension id, ...).
	Value string `yaml:"value,omitempty" json:"value,omitempty"`

	// int_value — the generic integer a set-style method writes (brightness,
	// dim_after, off_after, ...).
	IntValue int `yaml:"int_value,omitempty" json:"int_value,omitempty"`

	// settings — the raw JSON object a get/set settings method round-trips.
	Settings string `yaml:"settings,omitempty" json:"settings,omitempty"`

	// --- raw RPC escape hatch ---------------------------------------------
	// rpc_method — the device JSON-RPC method `rpc` invokes.
	RpcMethod string `yaml:"rpc_method,omitempty" json:"rpc_method,omitempty"`

	// rpc_params — the JSON object of params for `rpc`.
	RpcParams string `yaml:"rpc_params,omitempty" json:"rpc_params,omitempty"`

	// --- console OCR / installer -----------------------------------------
	// OCR is the read-only screen-reading method: capture the frame, run OCR
	// over it, and assert `text` (the field above, shared with `type`) is
	// present. It is the wait-for-screen primitive in `check:`/`run:` form (no
	// artifact required), the sibling of the `artifact_contains_text` validator
	// on `screenshot`.
	// install is the configurable console-wizard DRIVER (mutating): connect
	// once and walk an ordered `steps:` recipe, OCR-waiting for each screen's
	// anchor before sending its input. The recipe is generic DATA — the Omarchy
	// (or any) installer's screens are supplied by the entity, never hardcoded
	// here. It drives ANY text-console wizard: an OS installer, a first-boot
	// provisioning flow, a firmware setup screen.
	// steps — an INLINE recipe the `install` method drives (wins over the
	// entity recipe).
	Steps []JetkvmInstallStep `yaml:"steps,omitempty" json:"steps,omitempty"`

	// device — the name of a `kind: jetkvm` device entity whose named recipe
	// (`recipe:`) this step uses INSTEAD of inline steps:. The verb resolves it
	// out-of-process over its reverse channel, so recipes live in one place in
	// charly.yml and a bed references them by name.
	Device string `yaml:"device,omitempty" json:"device,omitempty"`

	// recipe — WHICH named recipe on the device entity to drive (default
	// "install"). A device can carry several — e.g. `install` for the OS
	// installer and `first_boot` for the post-reboot owner-provisioning wizard.
	Recipe string `yaml:"recipe,omitempty" json:"recipe,omitempty"`

	// answers — a name → value map `install` substitutes into every step's
	// `text` via `{{name}}` placeholders, so one recipe serves many machines
	// without editing the steps. The substitution is literal + single-pass
	// (NOT charly `${VAR}` expansion), independent of the check env.
	Answers map[string]string `yaml:"answers,omitempty" json:"answers,omitempty"`

	// answer_secrets — a name → CREDENTIAL-STORE KEY map, resolved at run time
	// and merged into `answers`. Use it for anything secret (a password, a LUKS
	// passphrase): the value is read from the credential store over the reverse
	// channel and NEVER appears in charly.yml. Explicit `answers` entries win.
	AnswerSecrets map[string]string `yaml:"answer_secrets,omitempty" json:"answer_secrets,omitempty"`

	// answers_env — a name → ENVIRONMENT-VARIABLE-NAME map, resolved at run time
	// and merged into `answers`. The fully-configurable-from-the-environment
	// path: the operator sets the env var and the recipe's {{placeholder}}
	// resolves to it, with nothing machine-specific committed. Precedence:
	// answers (authored) > answer_secrets > answers_env.
	AnswersEnv map[string]string `yaml:"answers_env,omitempty" json:"answers_env,omitempty"`

	// --- console terminal session (open / run / close / LUKS) -------------
	// `open-terminal`, `run-command`, `close-terminal` and `luks-unlock` drive
	// an INTERACTIVE shell (or the initramfs prompt) on the controlled machine,
	// reading each result by OCR. They share the transport-agnostic
	// kit.ConsoleSession engine, so the same methods serve the JetKVM and SPICE
	// transports (R3). The command COMPLETION is detected by an opaque marker the
	// shell echoes (never a prompt substring, which the terminal echo would
	// satisfy before the command ran — the RCA behind the marker design).
	//
	// open-terminal opens a terminal: it sends `terminal_combo` (default
	// "super+Return", Omarchy's terminal hotkey; use "ctrl+alt+F3" for a bare
	// text TTY) and OCR-waits for one of `prompt_anchors` (the shell prompt).
	// run-command runs `commands` in the open terminal, OCR-reading each result;
	// with `close_terminal: true` it exits afterwards. close-terminal exits an
	// open terminal (`exit`). luks-unlock types `passphrase` / its secret and
	// waits for one of `outcomes` (the boot proceeding, an error, a login).
	//
	// terminal_combo — the chord `open-terminal` sends (default "super+Return").
	TerminalCombo string `yaml:"terminal_combo,omitempty" json:"terminal_combo,omitempty"`

	// prompt_anchors — the substrings that mean a terminal is ready. Default
	// ["$", "#", ">"] (the common shell prompts). Screen-unique enough for the
	// readiness wait; override for an unusual prompt.
	PromptAnchors []string `yaml:"prompt_anchors,omitempty" json:"prompt_anchors,omitempty"`

	// commands — the ordered commands `run-command` executes.
	Commands []JetkvmSessionCommand `yaml:"commands,omitempty" json:"commands,omitempty"`

	// close_terminal — when true, `run-command` exits the terminal after the last
	// command (a convenience so one step opens, runs and closes).
	CloseTerminal bool `yaml:"close_terminal,omitempty" json:"close_terminal,omitempty"`

	// sudo_password — the password `run-command` types at a sudo prompt. Prefer
	// sudo_password_secret (the credential store); this literal exists for
	// ad-hoc/CI use and is never required when no command is `sudo: true`.
	SudoPassword string `yaml:"sudo_password,omitempty" json:"sudo_password,omitempty"`

	// sudo_password_secret — the credential-store key holding the sudo password.
	SudoPasswordSecret string `yaml:"sudo_password_secret,omitempty" json:"sudo_password_secret,omitempty"`

	// passphrase — the LUKS/disk-encryption passphrase `luks-unlock` types.
	// Prefer passphrase_secret.
	Passphrase string `yaml:"passphrase,omitempty" json:"passphrase,omitempty"`

	// passphrase_secret — the credential-store key holding the LUKS passphrase.
	PassphraseSecret string `yaml:"passphrase_secret,omitempty" json:"passphrase_secret,omitempty"`

	// outcomes — the SUCCESS anchors `luks-unlock` waits for (the boot
	// proceeding, a login prompt). A wrong passphrase is caught by a built-in
	// failure anchor set and FAILS the step, so this only names success.
	Outcomes []string `yaml:"outcomes,omitempty" json:"outcomes,omitempty"`

	// --- console FLOW (continuous OCR + if/then/else + case/switch + while) --
	// The `flow` method drives a BOUNDED STATE MACHINE over the console: each
	// node OCR-polls CONTINUOUSLY (never a guessed timeout) until one of its
	// NAMED outcomes appears, sends its action, then routes to the next node by
	// the OBSERVED outcome. A transition back to an earlier node is a while
	// loop, bounded by max_loops/max_steps so it can never spin forever.
	//
	// flow_start — the entry node id.
	FlowStart string `yaml:"flow_start,omitempty" json:"flow_start,omitempty"`

	// flow_nodes — id -> node. Each node: a `wait` list of named outcomes, an
	// optional `action`, `transitions` (outcome -> next id) for if/then/else and
	// case/switch, and a default `next`.
	FlowNodes map[string]JetkvmFlowNode `yaml:"flow_nodes,omitempty" json:"flow_nodes,omitempty"`

	// flow_max_steps / flow_max_loops — the loop bounds (defaults 200 / 50).
	FlowMaxSteps int `yaml:"flow_max_steps,omitempty" json:"flow_max_steps,omitempty"`

	FlowMaxLoops int `yaml:"flow_max_loops,omitempty" json:"flow_max_loops,omitempty"`

	// --- boot order (EFI boot manager, target-side over the terminal) ------
	// `boot-order` sets the UEFI boot order from INSIDE the running system, using
	// the EFI boot manager `efibootmgr` in an open terminal — the OS-side
	// counterpart to pressing the firmware boot-menu key (F11/F12). Actions:
	//
	//	list — run `efibootmgr` and return the entries (BootCurrent/BootOrder/
	//	       BootNNNN lines) read by OCR.
	//	next — one-time next boot: `efibootmgr --bootnext <entry>` (does NOT
	//	       change the persistent order; ideal for booting an installer medium
	//	       once, then returning to the disk).
	//	set  — persist the order: `efibootmgr --bootorder <sequence>`.
	BootOrderAction string `yaml:"boot_order_action,omitempty" json:"boot_order_action,omitempty"`

	// boot_order_entry — the entry number for action: next (e.g. "0003").
	BootOrderEntry string `yaml:"boot_order_entry,omitempty" json:"boot_order_entry,omitempty"`

	// boot_order_sequence — the comma-separated entry order for action: set
	// (e.g. "0003,0001,0002").
	BootOrderSequence string `yaml:"boot_order_sequence,omitempty" json:"boot_order_sequence,omitempty"`

	// boot_order_command — overrides the boot-manager binary (default
	// "efibootmgr"), for a system that names it differently.
	BootOrderCommand string `yaml:"boot_order_command,omitempty" json:"boot_order_command,omitempty"`

	// --- artifact ---------------------------------------------------------
	// artifact — the host path `screenshot` writes the PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir.
	ArtifactDir string `yaml:"artifact_dir,omitempty" json:"artifact_dir,omitempty"`

	// session_id — the detached-recorder session id (`session`).
	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	// state_dir — the detached recorder's state directory.
	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// fps — the detached recorder capture rate (default 5).
	Fps int `yaml:"fps,omitempty" json:"fps,omitempty"`

	// duration_sec — how long a recording/bounded capture runs.
	DurationSec int `yaml:"duration_sec,omitempty" json:"duration_sec,omitempty"`

	// log_dir — the detached recorder's log directory.
	LogDir string `yaml:"log_dir,omitempty" json:"log_dir,omitempty"`

	// venue / phase — stamped into the recorder's evidence row.
	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform /
	// artifact_contains_text — the post-run artifact-reality assertions
	// (sdk.RunArtifactValidators) THIS verb can produce. artifact_contains_text is
	// the OCR wait-for-screen primitive in `screenshot` form: it runs tesseract on
	// the HOST over the pulled PNG and asserts the text is present, so a
	// `screenshot` step can gate on what the screen actually shows.
	//
	// artifact_min_cast_events is deliberately NOT here: it validates an asciinema
	// `.cast` file, and the jetkvm verb produces only PNGs — the field would be
	// dead surface, so it is omitted rather than shipped unexercised.
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	ArtifactContainsText string `yaml:"artifact_contains_text,omitempty" json:"artifact_contains_text,omitempty"`
}

// #JetkvmMethod — the method catalog. Grouped by intent so the read-only
// surface is separable from the mutating one (the allow_control gate).
//
// NOTE: written as a bare trailing-pipe disjunction, NOT `(...)`-wrapped: CUE
// does not terminate a parenthesised expression at a newline, so the grouped
// form requires commas and breaks `cue exp gengotypes`.
type JetkvmMethod string

// #JetkvmMacroStep — one step of a keyboard macro.
type JetkvmMacroStep struct {
	Keys []string `yaml:"keys,omitempty" json:"keys,omitempty"`

	Modifiers []string `yaml:"modifiers,omitempty" json:"modifiers,omitempty"`

	Delay int64 `yaml:"delay,omitempty" json:"delay,omitempty"`
}

// #JetkvmAction — the union of every action verb the action-bearing methods
// accept. It is the CUE-expressible half of the action contract: the SET of legal
// verbs is enforced here at validate time (a typo fails before any device call).
//
// WHY NOT A PER-METHOD DISJUNCTION (SDD): the natural shape would be one action
// field carrying `if method == "power" { action: "power-short" | ... }` rules.
// That is INEXPRESSIBLE without degrading `cue exp gengotypes`: a conditional
// that constrains a field to a method-specific set evaluates with `method` still
// abstract, every branch stays unresolved, and the generator emits the WHOLE
// struct as `any` (measured — the same limitation documented at
// spec/schema/vm.cue's #LibvirtGraphics note). The method-SPECIFIC subset is
// therefore enforced at dispatch, which is also where the error can name the
// method. The union below keeps the generator healthy.
type JetkvmAction string

// #JetkvmInstallStep — ONE step of a console-installer recipe driven by the
// `install` method. Each step OCR-waits for its `wait_for` anchor to appear on
// the screen, then performs ONE input action.
//
// A REAL WIZARD recipe MUST use a screen-UNIQUE anchor per step: a string present
// on every screen (e.g. a logo) passes vacuously and desynchronises the whole
// drive. A single-step PROBE recipe whose only job is to prove the OCR read and
// the transport's input may deliberately use a broad anchor — there is no next
// step to desynchronise against — and the entity bed's `probe` recipe is exactly
// that.
type JetkvmInstallStep struct {
	// wait_for — the text the step waits for before acting. Screen-unique for a
	// multi-step wizard recipe; a single-step probe may use a broad anchor.
	WaitFor string `yaml:"wait_for,omitempty" json:"wait_for"`

	// action — the input to send once `wait_for` is on screen. Omitted means the
	// step only waits (a pure synchronisation/observation step).
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// key — the named key for action: key (Return, Escape, F5, ...).
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// combo — the chord for action: key-combo (ctrl+c, ctrl+alt+Delete, ...).
	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	// text — the text for action: type.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// timeout_sec — how long to wait for `wait_for` before failing (default 120).
	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`

	// optional — when true, a wait that times out (the anchor never appears)
	// SKIPS the step instead of failing the drive, and its action is not sent.
	// Use it for a screen that is only sometimes present (a keyboard picker on a
	// machine that already recorded one, an install-mode picker only offered when
	// free space exists) — so one recipe serves both shapes.
	Optional bool `yaml:"optional,omitempty" json:"optional,omitempty"`

	// artifact — optional host path to save the frame captured for this step.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// description — optional human label for the step's evidence line.
	Description string `yaml:"description,omitempty" json:"description,omitempty"`
}

// #JetkvmSessionCommand — ONE command the `run-command` method runs in an OPEN
// terminal session, reading its result by OCR.
type JetkvmSessionCommand struct {
	// command — the shell command line to run.
	Command string `yaml:"command,omitempty" json:"command"`

	// sudo — run through sudo (prefixed with `sudo `), entering the session's
	// sudo password at the prompt when the target asks for it.
	Sudo bool `yaml:"sudo,omitempty" json:"sudo,omitempty"`

	// expect — optional substring that MUST appear in the OCR-read result; when
	// set and absent the command fails naming what was read. It is the
	// assertion half of "read the results via OCR".
	Expect string `yaml:"expect,omitempty" json:"expect,omitempty"`

	// timeout_sec — how long to wait for the completion marker (default 120).
	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`

	// artifact — optional host path the completion frame is written to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// description — optional human label.
	Description string `yaml:"description,omitempty" json:"description,omitempty"`
}

// #JetkvmFlowNode — ONE state of a console flow. It OCR-polls for a `wait`
// outcome, sends `action`, then routes by the observed outcome.
type JetkvmFlowNode struct {
	// description — optional human label for the evidence line.
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	// wait — the named outcomes to OCR-poll for. Empty = act immediately.
	Wait []JetkvmFlowOutcome `yaml:"wait,omitempty" json:"wait,omitempty"`

	// action — what to send once a wait matched (or immediately). At most one of
	// the fields is used.
	Key string `yaml:"key,omitempty" json:"key,omitempty"`

	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// command / sudo / expect — run a shell command in the OPEN terminal and read
	// its output by OCR (the same marker-completed path as `run-command`).
	Command string `yaml:"command,omitempty" json:"command,omitempty"`

	Sudo bool `yaml:"sudo,omitempty" json:"sudo,omitempty"`

	Expect string `yaml:"expect,omitempty" json:"expect,omitempty"`

	CloseTerminal bool `yaml:"close_terminal,omitempty" json:"close_terminal,omitempty"`

	// transitions — outcome name -> next node id (if/then/else, case/switch). A
	// matched outcome with no entry falls through to `next`.
	Transitions map[string]string `yaml:"transitions,omitempty" json:"transitions,omitempty"`

	// next — the default target when the matched outcome has no transition.
	Next string `yaml:"next,omitempty" json:"next,omitempty"`

	// artifact — optional host path saving the frame captured at this node.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// timeout_sec — bounds this node's OCR poll (default 120).
	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`
}

// #JetkvmFlowOutcome — ONE named condition a flow node waits for. The engine
// OCR-polls continuously until any outcome's `match` substring is on screen.
type JetkvmFlowOutcome struct {
	// name — the outcome identifier, keyed in a node's `transitions`.
	Name string `yaml:"name,omitempty" json:"name"`

	// match — the case-insensitive substring that identifies this outcome.
	Match string `yaml:"match,omitempty" json:"match"`

	// failure — marks a failure outcome (a wrong-passphrase / error screen). It
	// fails the flow unless a `transitions` entry routes it (a recovery branch).
	Failure bool `yaml:"failure,omitempty" json:"failure,omitempty"`
}

// #JetkvmDeviceInput — the authored `kind: jetkvm` DEVICE entity body. It is
// the plugin's configurable surface: the device address + credentials, and an
// optional installer recipe + answers. Consumed by the plugin's OpLoad (to
// store the typed entity) and used by `charly jetkvm install <entity>` and by
// a local/VM deploy that names it.
type JetkvmDeviceInput struct {
	// host — the device address. Omit to fall back to JETKVM_HOST at runtime.
	Host string `yaml:"host,omitempty" json:"host,omitempty"`

	// insecure — permit the device's self-signed TLS certificate.
	Insecure bool `yaml:"insecure,omitempty" json:"insecure,omitempty"`

	// password_secret — credential-store key holding the device password.
	PasswordSecret string `yaml:"password_secret,omitempty" json:"password_secret,omitempty"`

	// description — human label for the device.
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	// installer — the console-installer recipe + answers for this device.
	Installer *JetkvmInstaller `yaml:"installer,omitempty" json:"installer,omitempty"`
}

// #JetkvmInstaller — the installer/wizard configuration for a `kind: jetkvm`
// device. One device can carry SEVERAL named recipes (an OS installer AND the
// post-reboot first-boot provisioning wizard are two), each a named `steps:`
// list under `recipes:`.
type JetkvmInstaller struct {
	// recipes — name → ordered recipe. The conventional names are `install`
	// (the OS installer, the default) and `first_boot` (the post-reboot owner
	// provisioning wizard), but any name works: a step selects one with
	// `recipe:`.
	Recipes map[string][]JetkvmInstallStep `yaml:"recipes,omitempty" json:"recipes,omitempty"`

	// steps — a SHORTCUT for recipes.install, so a single-recipe device needs no
	// nesting. If both are set, `recipes.install` wins.
	Steps []JetkvmInstallStep `yaml:"steps,omitempty" json:"steps,omitempty"`

	// answers — a name → value map the install driver substitutes into step
	// `text` fields via `{{name}}` placeholders.
	Answers map[string]string `yaml:"answers,omitempty" json:"answers,omitempty"`

	// answer_secrets — a name → credential-store key map, resolved at run time
	// and merged into answers. Use for secrets so nothing plaintext is committed.
	AnswerSecrets map[string]string `yaml:"answer_secrets,omitempty" json:"answer_secrets,omitempty"`

	// answers_env — a name → environment-variable-name map, resolved at run time
	// and merged into answers (lowest precedence). The environment-configurable
	// path: nothing machine-specific is committed.
	AnswersEnv map[string]string `yaml:"answers_env,omitempty" json:"answers_env,omitempty"`
}
