// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `jetkvm` plugin's OWN CUE schema — the typed plugin_input for the
// `jetkvm` IP-KVM check/control verb.
//
// It is the SINGLE SOURCE for this plugin's params, used two ways (the same
// contract core `spec` and every other plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the
//     cue:gen pipeline, which wraps this with `package params` + `@go(params)`)
//     emits ../params/cue_types_gen.go, so the provider decodes plugin_input
//     into a TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over
//     the Describe channel; the host splices it onto the base (base ++ plugin)
//     and validates every authored `jetkvm:` step's plugin_input against
//     #JetkvmInput.
//
// An authored `jetkvm: <method>` step (scalar sugar) or
// `jetkvm: {method: …, x: …}` (map form) desugars to the INTERNAL
// plugin/plugin_input envelope, and every jetkvm-exclusive modifier lives
// HERE. The shared assertion matchers (exit_status/stdout/stderr) and the
// general `timeout` stay on core #Op, read off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type JetkvmInput struct {
	// method — the jetkvm method to dispatch (also the scalar-sugar primary:
	// `jetkvm: <method>`).
	Method JetkvmMethod `json:"method"`

	// --- connection -------------------------------------------------------
	// host — the device address ("host", "host:port", or an http(s) URL). When
	// omitted the provider falls back to the deploy's venue address.
	Host string `json:"host,omitempty"`

	// password — the device password. Prefer password_secret (the credential
	// store); this literal exists for ad-hoc/CI use.
	Password string `json:"password,omitempty"`

	// password_secret — the credential-store key holding the device password.
	PasswordSecret string `json:"password_secret,omitempty"`

	// auth_token — an already-valid authToken session cookie value, skipping login.
	AuthToken string `json:"auth_token,omitempty"`

	// allow_control — REQUIRED to be true for every mutating method (input,
	// power, USB, virtual media, config writes). Read-only methods ignore it.
	// This is the device-safety gate: a physical appliance is not disposable.
	AllowControl bool `json:"allow_control,omitempty"`

	// insecure — permit a self-signed TLS certificate (the device ships
	// self-signed by default). Also implied by an http:// host.
	Insecure bool `json:"insecure,omitempty"`

	// --- input (keyboard/pointer) ----------------------------------------
	// text — the text `type` types.
	Text string `json:"text,omitempty"`

	// key — the named key `key` presses (Return, Escape, F5, Control_L, ...).
	KeyName string `json:"key,omitempty"`

	// combo — the chord `key-combo` presses, e.g. "Control_L+Alt_L+Delete".
	Combo string `json:"combo,omitempty"`

	// hold_ms — how long `key`/`combo` holds before release (default 40).
	HoldMs int `json:"hold_ms,omitempty"`

	// x / y — desktop-absolute coordinates (click/mouse/move/drag to).
	X int `json:"x,omitempty"`

	Y int `json:"y,omitempty"`

	// from_x / from_y — drag start coordinates.
	FromX int `json:"from_x,omitempty"`

	FromY int `json:"from_y,omitempty"`

	// button — pointer button (left/right/middle; default left).
	Button string `json:"button,omitempty"`

	// scroll_x / scroll_y — wheel deltas (scroll).
	ScrollX int `json:"scroll_x,omitempty"`

	ScrollY int `json:"scroll_y,omitempty"`

	// macro — the ordered key-steps a `macro` method executes.
	Macro []JetkvmMacroStep `json:"macro,omitempty"`

	// --- power / ATX / DC -------------------------------------------------
	// action — the power action: power-short | power-long | reset | on | off |
	// restore-on | restore-off | restore-last.
	Action string `json:"action,omitempty"`

	// --- virtual media ----------------------------------------------------
	// media_url — the HTTP(S) URL `virtual-media` mounts.
	MediaUrl string `json:"media_url,omitempty"`

	// media_file — the device-storage filename `virtual-media` mounts/deletes.
	MediaFile string `json:"media_file,omitempty"`

	// media_mode — cdrom | disk.
	MediaMode string `json:"media_mode,omitempty"`

	// --- usb --------------------------------------------------------------
	// usb_device — absolute_mouse | relative_mouse | keyboard | mass_storage |
	// serial_console | audio.
	UsbDevice string `json:"usb_device,omitempty"`

	// usb_enabled — enable/disable the addressed usb_device (or the whole
	// emulation bus for `usb-emulation`).
	UsbEnabled bool `json:"usb_enabled,omitempty"`

	// --- config / network -------------------------------------------------
	// value — the generic scalar a set-style method writes (rotation, layout,
	// codec, factor, log level, extension id, ...).
	Value string `json:"value,omitempty"`

	// int_value — the generic integer a set-style method writes (brightness,
	// dim_after, off_after, ...).
	IntValue int `json:"int_value,omitempty"`

	// settings — the raw JSON object a get/set settings method round-trips.
	Settings string `json:"settings,omitempty"`

	// --- raw RPC escape hatch ---------------------------------------------
	// rpc_method — the device JSON-RPC method `rpc` invokes.
	RpcMethod string `json:"rpc_method,omitempty"`

	// rpc_params — the JSON object of params for `rpc`.
	RpcParams string `json:"rpc_params,omitempty"`

	// --- artifact ---------------------------------------------------------
	// artifact — the host path `screenshot` writes the PNG to.
	Artifact string `json:"artifact,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir.
	ArtifactDir string `json:"artifact_dir,omitempty"`

	// session_id — the detached-recorder session id (`session`).
	SessionId string `json:"session_id,omitempty"`

	// state_dir — the detached recorder's state directory.
	StateDir string `json:"state_dir,omitempty"`

	// fps — the detached recorder capture rate (default 5).
	Fps int `json:"fps,omitempty"`

	// duration_sec — how long a recording/bounded capture runs.
	DurationSec int `json:"duration_sec,omitempty"`

	// log_dir — the detached recorder's log directory.
	LogDir string `json:"log_dir,omitempty"`

	// venue / phase — stamped into the recorder's evidence row.
	Venue string `json:"venue,omitempty"`

	Phase string `json:"phase,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform —
	// the post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `json:"artifact_not_uniform,omitempty"`
}

// #JetkvmMethod — the method catalog. Grouped by intent so the read-only
// surface is separable from the mutating one (the allow_control gate).
//
// NOTE: written as a bare trailing-pipe disjunction, NOT `(...)`-wrapped: CUE
// does not terminate a parenthesised expression at a newline, so the grouped
// form requires commas and breaks `cue exp gengotypes`.
type JetkvmMethod string

// #JetkvmMacroStep — one step of a keyboard macro.
type JetkvmMacroStep struct {
	Keys []string `json:"keys,omitempty"`

	Modifiers []string `json:"modifiers,omitempty"`

	Delay int64 `json:"delay,omitempty"`
}
